name: awesome_3d_button
description: 3D button widget for Flutter
version: 1.0.0
homepage: https://github.com/heda7/awesome_3d_button

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true